### ISSUE TITLE
Installation broken with `0.17.0.post1` with poetry due to git / flash infer dependency. 

### ISSUE THREAD

**Issue by michaelfeil** [NVIDIA/TensorRT-LLM#2774]
### System Info

Summary: Hitting `https://github.com/flashinfer-ai/flashinfer.git at '06309c4e', verify ref exists on remote.` on `post1`

Running the following pyproject.toml

```toml
[tool.poetry.dependencies]
python = "3.10.12"
torch = ">=2.5.1"

# Hack for TensorRT with PEP 517 builds https://github.com/NVIDIA/TensorRT/issues/3362
# when making changes to TRT-LLM version, pin associated tensorrt_libs, tensorrt_bindings, and tensorrt version
# https://github.com/NVIDIA/TensorRT/issues/3945#issuecomment-2174117182
tensorrt_cu12_libs     = { version = "10.8.0", source = "nvidia", platform = "linux"}
tensorrt_cu12_bindings = { version = "10.8.0", source = "nvidia", platform = "linux" }
tensorrt-cu12          = { version = "10.8.0", source = "nvidia", platform = "linux" }
tensorrt_llm           = { version = "0.17.0.post1", source = "nvidia", platform = "linux" } #{ url = "https://pypi.nvidia.com/tensorrt-llm/tensorrt_llm-0.17.0.post1-cp310-cp310-linux_x86_64.whl"}

[[tool.poetry.source]]
name = "nvidia"
url = "https://pypi.nvidia.com"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Leads to:
```
# poetry lock --no-update
Resolving dependencies... (5.5s)

Failed to clone https://github.com/flashinfer-ai/flashinfer.git at '06309c4e', verify ref exists on remote.
```

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

-

### Expected behavior

-

### actual behavior

-

### additional notes

-
