### ISSUE TITLE
Executor API: How to get throughput

### ISSUE THREAD

**Issue by khayamgondal** [NVIDIA/TensorRT-LLM#3142]
I am looking at [benchmarks](https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks)/[python](https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks/python)/[kv_cache_offload](https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks/python/kv_cache_offload)
/benchmark.py example and trying to figure out how can I get throughput. This example gets TTFT from `executor.get_latest_iteration_stats().` I looked at get_latest_iteration_stats() definitions but didn't find any information regarding how to get throughput. 
Here is what is available via get_latest_iteration_stats() function 
`'cpu_mem_usage', 'cross_kv_cache_stats', 'gpu_mem_usage', 'inflight_batching_stats', 'iter', 'iter_latency_ms', 'kv_cache_stats', 'max_num_active_requests', 'new_active_requests_queue_latency_ms', 'num_active_requests', 'num_completed_requests', 'num_new_active_requests', 'num_queued_requests', 'pinned_mem_usage', 'static_batching_stats', 'timestamp', 'to_json_str']`

**Comment by juney-nvidia** [comment]
Hi @khayamgondal 

The throughput information should be stored in [inflight_batching_stats](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/pybind/executor/bindings.cpp#L152) .

Also we are moving to use [trtllm-bench](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance/perf-benchmarking.md) to consolidate the performance benchmarking process which I would suggest you to refer.

For any specific question about this kv_cache_offload benchmark script, @SimengLiu-nv may help.

For any question about trtllm-bench, @FrankD412  @kaiyux @jiahanc can help.

Thanks
June

**Comment by SimengLiu-nv** [comment]
Hi @khayamgondal , the end-to-end throughput statistics are calculated not directly reported. For example, `Token Throughput (tokens/sec) = total_output_tokens / total_latency`. `Request Throughput (req/sec) = total_num_requests /  total_latency.` For the value of `total_latency`, you can convert the logged E2E TIME (ms) to second.

**Comment by khayamgondal** [comment]
Thanks @juney-nvidia how do I use` trtllm.KvCacheConfig `with` trtllm-bench`?

**Comment by kaiyux** [comment]
> Thanks [@juney-nvidia](https://github.com/juney-nvidia) how do I use`trtllm.KvCacheConfig`with` trtllm-bench`?

@khayamgondal There is a [`--extra_llm_api_options`](https://github.com/NVIDIA/TensorRT-LLM/blob/8bb3eea285db15c3b54c66230eb2701505fc863f/tensorrt_llm/bench/benchmark/throughput.py#L49) argument provided by `trtllm-bench` that allows you to specify any custom configurations following [`LlmArgs`](https://github.com/NVIDIA/TensorRT-LLM/blob/8bb3eea285db15c3b54c66230eb2701505fc863f/tensorrt_llm/llmapi/llm_args.py#L760) data structure, and that includes `kv_cache_config`.

Let me know for further questions, thanks.

**Comment by FrankD412** [comment]
@khayamgondal -- you should be able to specify a KV cache config via an extra options YML file. It would look something like:

```yaml
kv_cache_config:
  free_gpu_memory_fraction: 0.95
  enable_block_reuse: true
```

You can find the specific arguments to the `KvCacheConfig` [here])https://github.com/NVIDIA/TensorRT-LLM/blob/8bb3eea285db15c3b54c66230eb2701505fc863f/tensorrt_llm/llmapi/llm_args.py#L520). As @kaiyux mentioned, you can pass this in via `--extra_llm_api_options` (and it isn't limited to just the KV cache. A caveat is that if you modify an entry, none of the configuration set by `trtllm-bench` will hold so make sure you set everything (even if `trtllm-bench` does set it).

**Comment by khayamgondal** [comment]
Thanks @FrankD412  is there a way to dump default values set by `trtllm-bench` ? 

Based on` llm_ags.py` looks like I need following

```
kv_cache_config:
    enable_block_reuse: true
    max_tokens: 17800
    max_attention_window: null
    sink_token_length: null
    free_gpu_memory_fraction: 0.9
    host_cache_size: null
    onboard_blocks: true
    cross_kv_cache_fraction: null
    secondary_offload_min_priority: null
    event_buffer_max_size: 0
    enable_partial_reuse: true
    copy_on_partial_reuse: true
```
