### ISSUE TITLE
deepseek-fp4 quality issue -- bad generation output after the second batch run

### ISSUE THREAD

**Issue by xwuShirley** [NVIDIA/TensorRT-LLM#4072]
Docker images: 
you could build the docker image with the following command
```
git clone --single-branch --branch main https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git checkout main
git pull
git checkout 5502a522d22a7770d0e6d04b33bce6a38793ce5f
git submodule update --init --recursive
git lfs pull
make -C docker release_build
```

Start the serving: 

```
export HUGGINGFACE_HUB_CACHE=/data/huggingface/ 
MODEL_NAME=nvidia/DeepSeek-R1-FP4    
cat >./extra-llm-api-config.yml<<EOF
pytorch_backend_config:
    enable_overlap_scheduler: true
    use_cuda_graph: true
speculative_config:
    decoding_type: MTP
    num_nextn_predict_layers: 3
EOF
trtllm-serve ${MODEL_NAME} --backend pytorch --host 0.0.0.0 --port 8001 \
    --backend pytorch \
    --max_batch_size 32 \
    --tp_size 8 \
    --ep_size 4 \
    --extra_llm_api_options ./extra-llm-api-config.yml
```

We do large batch queries
Use https://github.com/lmarena/arena-hard-auto (follow the instruction to do the installation)
update the yaml file https://github.com/lmarena/arena-hard-auto/blob/main/config/api_config.yaml with
```
deepseek-r1-fp4:
    model: nvidia/DeepSeek-R1-FP4
    endpoints:
        - api_base: http://0.0.0.0:8001/v1
          api_key: '-'
    api_type: openai
    parallel: 128
    max_tokens: 8196
    temperature: 0.0
```
and gen_answer_config.yaml
```
bench_name: arena-hard-v2.0
model_list:
  - deepseek-r1-fp4
```
Run `python gen_answer.py`
The first time, you will get good reasonable output: 
The second time you will see that the output sequence length started to decrease 
The third time you will see that the output token is 1!
