### ISSUE TITLE
[Nvidia A10G + _torch flow]: No fused attention + OOM for 2048 context length

### ISSUE THREAD

**Issue by michaelfeil** [NVIDIA/TensorRT-LLM#4917]
### System Info

Related to build arguments.

```
model_name: unsloth/Llama-3.2-1B-Instruct
tensor_parallel_size: 1
moe_expert_parallel_size: 1
backend: pytorch
enable_chunked_prefill: true

kv_cache_config:
  free_gpu_memory_fraction: 0.6
  event_buffer_max_size: 1024
  enable_block_reuse: true

pytorch_backend_config:
  enable_overlap_scheduler: true
  use_cuda_graph: true
  enable_iter_perf_stats: true

build_config:
  max_num_tokens: 8192
  max_input_len: 2048
  max_seq_len: 2048
  max_beam_width: 1
  max_batch_size: 128
```

```
025-06-03 23:56:40,458 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
[TensorRT-LLM] TensorRT-LLM version: 0.19.0
[TensorRT-LLM][INFO] Refreshed the MPI local session

Loading weights:   0%|          | 0/329 [00:00<?, ?it/s]
Loading weights:   9%|▉         | 30/329 [00:00<00:01, 296.85it/s]
Loading weights:  48%|████▊     | 157/329 [00:00<00:00, 848.18it/s]
Model init total -- 0.89s
Loading weights:  85%|████████▍ | 279/329 [00:00<00:00, 1013.71it/s]
Loading weights: 100%|██████████| 329/329 [00:00<00:00, 976.42it/s] 
[TensorRT-LLM][INFO] Number of tokens per block: 32.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 0.25 GiB for max tokens in paged KV cache (8192).
2025-06-03 23:56:42,433 - INFO - flashinfer.jit: Loading JIT ops: norm
2025-06-03 23:57:08,280 - INFO - flashinfer.jit: Finished loading JIT ops: norm
Warning: -LLM][WARNING] FMHA kernels are not found with these parameters:
  S                     : 0
  D                     : 64
  DV                    : 64
  AttentionMaskType     : 1
  AttentionInputLayout  : 2
  AttnLogitSoftcapping  : 0
  AlibiSupported        : 0
  WarpSpecialization    : 0
  Tiled                 : 0
  FP32Accumulation      : 0
  FlashAttention        : 0
  Interleaved           : 0
  Unroll                : 0
  Hash                  : 0x0000000200800c00

Available kernel functions:

Warning: -LLM][WARNING] FMHA Kernel doesn't exist for mFixedParams:
dataType = bf16, dataTypeKv = bf16, dataTypeOut = bf16, forceFp32Acc = false, attentionMaskType = causal, attentionInputLayout = q_paged_kv, isSPadded = false, numQHeads = 32, numKvHeads = 8, numTokensPerBlock = 32, headSize = 64, headSizeV = 64, qScaling = 1.000000, attnLogitSoftcappingScale = 0.000000, hasAlibi = false, scaleAlibi = false, tpSize = 1, tpRank = 0, sageBlockSizeQ = 0, sageBlockSizeK = 0, sageBlockSizeV = 0

Warning: -LLM][WARNING] Fall back to unfused MHA for dataType = bf16, dataTypeKv = bf16, dataTypeOut = bf16, forceFp32Acc = false, attentionMaskType = causal, attentionInputLayout = q_paged_kv, isSPadded = false, numQHeads = 32, numKvHeads = 8, numTokensPerBlock = 32, headSize = 64, headSizeV = 64, qScaling = 1.000000, attnLogitSoftcappingScale = 0.000000, hasAlibi = false, scaleAlibi = false, tpSize = 1, tpRank = 0, sageBlockSizeQ = 0, sageBlockSizeK = 0, sageBlockSizeV = 0 in sm_86.
[06/03/2025-23:57:10] [TRT-LLM] [E] Failed to initialize executor on rank 0: CUDA out of memory. Tried to allocate 97.55 GiB. GPU 0 has a total capacity of 22.18 GiB of which 18.50 GiB is free. Process [249](https://github.com/basetenlabs/baseten/actions/runs/15430076885/job/43426000896#step:7:250)151 has 268.00 MiB memory in use. Process 249701 has 3.41 GiB memory in use. Of the allocated memory 2.37 GiB is allocated by PyTorch, and 477.61 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

Also not working for other basic llama architectures. 
```
Warning: -LLM][WARNING] FMHA Kernel doesn't exist for mFixedParams:
dataType = bf16, dataTypeKv = bf16, dataTypeOut = bf16, forceFp32Acc = false, attentionMaskType = causal, attentionInputLayout = q_paged_kv, isSPadded = false, numQHeads = 24, numKvHeads = 8, numTokensPerBlock = 32, headSize = 128, headSizeV = 128, qScaling = 1.000000, attnLogitSoftcappingScale = 0.000000, hasAlibi = false, scaleAlibi = false, tpSize = 1, tpRank = 0, sageBlockSizeQ = 0, sageBlockSizeK = 0, sageBlockSizeV = 0
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

start on A10G with the above command for LLM API (runs via torch flow)

### Expected behavior

We are trying get any model running on A10G, this is currently not working

### actual behavior

-

### additional notes

-

**Comment by VALLIS-NERIA** [comment]
Hi @michaelfeil , can you share the command to build TRTLLM? e.g. `make -C docker release_run CUDA_ARCHS="xxx"` or `build_wheel.py -a "xxx"`

**Comment by michaelfeil** [comment]
Adding 80-real,86-real,89-real to below command. 

```
BUILD_WHEEL_ARGS="--clean --benchmarks --python_bindings --trt_root /usr/local/tensorrt --cuda_architectures 90-real;100-real"
```

**Comment by yuxianq** [comment]
@michaelfeil  This issue have been fixed on latest main branch, cannot reproduce now.
Here is my repro commands:

Config file `tmp/config.yaml`:
```
max_batch_size: 128
max_num_tokens: 8196
max_seq_len: 2049
tensor_parallel_size: 1
moe_expert_parallel_size: 1
enable_attention_dp: false
pipeline_parallel_size: 1
print_iter_log: true
cuda_graph_config:
  max_batch_size: 128
  enable_padding: true
disable_overlap_scheduler: false
kv_cache_config:
  enable_block_reuse: true
  free_gpu_memory_fraction: 0.6
```

Run benchmark:
```
MODEL_DIR="unsloth/Llama-3.2-1B-Instruct"
NUM_REQUESTS=64
ISL=2048
OSL=1
TP=1
EP=1
PP=1

DATASET="tmp/dataset_r1_ISL${ISL}_OSL${OSL}.json"
LOGFILE="tmp/log_agg_ISL${ISL}_OSL${OSL}.txt"
CONFIG="tmp/config.yaml"

# check if the dataset exists
if [ ! -f ${DATASET} ]; then
    python benchmarks/cpp/prepare_dataset.py \
        --stdout \
        --tokenizer ${MODEL_DIR} \
        token-unif-dist \
        --input-min ${ISL} \
        --input-max ${ISL} \
        --output-min ${OSL} \
        --output-max ${OSL} \
        --num-requests ${NUM_REQUESTS} > ${DATASET}
fi

trtllm-bench \
    --model ${MODEL_DIR} \
    throughput \
    --tp ${TP} --ep ${EP} --pp ${PP} \
    --num_requests ${NUM_REQUESTS} \
    --extra_llm_api_options ${CONFIG} \
    --backend pytorch \
    --dataset ${DATASET} \
    2>&1 | tee ${LOGFILE}
```

Please reopen it if you meet the same issue on main branch.
